@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiZW1haWwiOiJ1c2VyMTIzQGV4YW1wbGUuY29tIiwiaWF0IjoxNzY1MjU3NjExLCJleHAiOjE3NjUyNjEyMTF9.m4tcm92vqezlUzcw3ocSPqCefE9il6VxT9nmp4E0xNQ

### Dev Login
POST http://localhost:3000/api/auth/dev/login
Content-Type: application/json

{
    "userId": "user123",
    "email": "user123@example.com"
}

### Initiate upload
POST http://localhost:3000/api/files/initiate
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "userId": "user123",
    "originalFilename": "santa.jpg",
    "mimeType": "image/jpeg",
    "sizeBytes": 30801
}

### Complete upload
POST http://localhost:3000/api/files/complete
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "fileId": "ffab8492-33cd-43c3-b596-eed5f8ce0d2c",
    "storageKey": "raw/user123/ffab8492-33cd-43c3-b596-eed5f8ce0d2c-santa.jpg",
    "userId": "user123"
}

### Get file
GET http://localhost:3000/api/files
Authorization: Bearer {{token}}

### Delete for user
DELETE http://localhost:3000/api/files/user
Authorization: Bearer {{token}}

### Delete single file
DELETE http://localhost:3000/api/files/file/ffab8492-33cd-43c3-b596-eed5f8ce0d2c
Authorization: Bearer {{token}}
