export type JobStatus = 'QUEUED' | 'PROCESSING' | 'COMPLETED' | 'FAILED_RETRYABLE' | 'FAILED';

export enum JobStatusEnum {
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED_RETRYABLE = 'FAILED_RETRYABLE',
  FAILED = 'FAILED',
}
